const playButton = document.querySelector('.play-button'); const audioPlayer = document.getElementById('fallback-player'); const loader = document.getElementById('loading-circle'); const playToggle = document.getElementById('playToggle'); const statusText = document.getElementById('statusText'); const playlistItems = document.querySelectorAll('#playlist li');

let isPlaying = false; let currentTrack = document.querySelector('#playlist li.active'); audioPlayer.src = currentTrack.dataset.src;

// Play button (de sus) playButton.addEventListener('click', () => { if (!isPlaying) { loader.style.display = 'block'; audioPlayer.play() .then(() => { isPlaying = true; loader.style.display = 'none'; playButton.textContent = 'Now Playing'; playButton.style.backgroundColor = '#28a745'; playToggle.innerHTML = '<i class="fas fa-pause"></i>'; statusText.textContent = 'Live Now'; }) .catch((error) => { console.error('Eroare la redare:', error); loader.style.display = 'none'; alert('Nu s-a putut porni radioul. Încearcă din nou.'); }); } else { audioPlayer.pause(); isPlaying = false; playButton.textContent = 'Play Radio'; playButton.style.backgroundColor = '#ff007f'; playToggle.innerHTML = '<i class="fas fa-play"></i>'; statusText.textContent = 'Off Air'; } });

// Custom player toggle playToggle.addEventListener('click', () => { if (!isPlaying) { audioPlayer.play().then(() => { isPlaying = true; playToggle.innerHTML = '<i class="fas fa-pause"></i>'; statusText.textContent = 'Live Now'; playButton.textContent = 'Now Playing'; playButton.style.backgroundColor = '#28a745'; }); } else { audioPlayer.pause(); isPlaying = false; playToggle.innerHTML = '<i class="fas fa-play"></i>'; statusText.textContent = 'Off Air'; playButton.textContent = 'Play Radio'; playButton.style.backgroundColor = '#ff007f'; } });

// Playlist click playlistItems.forEach(item => { item.addEventListener('click', () => { playlistItems.forEach(li => li.classList.remove('active')); item.classList.add('active'); audioPlayer.src = item.dataset.src; audioPlayer.play(); isPlaying = true; playToggle.innerHTML = '<i class="fas fa-pause"></i>'; statusText.textContent = 'Now Playing: ' + item.textContent; playButton.textContent = 'Now Playing'; playButton.style.backgroundColor = '#28a745'; }); });

